version: "3.7"

services: 
    api:
        image: node:12-alpine
        command: sh -c "npm install && node index.js"
        ports: 
            - 3000:3000
        working_dir: /api
        volumes: 
            - ${PWD}/api:/api
    pg:
        image: postgres:13-alpine
        ports:
            - 7000:7000
        volumes:
            - ${PWD}/db:/var/lib/postgresql/data
            - ${PWD}/sql:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: me 
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sp_test
